apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vmaas

resources:
  - cloudkit.openshift.io_virtualmachines.yaml

labels:
- pairs:
    cloudkit.openshift.io/project: cloudkit-vmaas
